### ISSUE TITLE
希望可以升级到最新版本 

### ISSUE THREAD

**Issue by DUWENINK** [ldqk/Masuit.Tools#10]
执行 `Install-Package Masuit.Tools.Core`
返回 ` Install-Package : NU1605: 检测到包降级: Microsoft.Extensions.DependencyInjection 从 3.1.2 降级到 3.1.0。直接从项目引用包以选择不同版本。 
 Coldairarrow.Api -> Masuit.Tools.Core 2.2.8.4 -> Microsoft.EntityFrameworkCore 3.1.2 -> Microsoft.Extensions.DependencyInjection (>= 3.1.2) 
 Coldairarrow.Api -> Microsoft.Extensions.DependencyInjection (>= 3.1.0)
所在位置 行:1 字符: 1
+ Install-Package Masuit.Tools.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: 检测到包降级: Microsoft.Extensions.DependencyInjection 从 3.1.2 降级到 3.1.0。直接从项目引用包以选择不同版本。 
 Coldairarrow.Api -> Masuit.Tools.Core 2.2.8.4 -> Microsoft.Extensions.Http 3.1.2 -> Microsoft.Extensions.Logging 3.1.2 -> Microsoft.Extensions.DependencyInjection (>= 3.1.2) 
 Coldairarrow.Api -> Microsoft.Extensions.DependencyInjection (>= 3.1.0)
所在位置 行:1 字符: 1
+ Install-Package Masuit.Tools.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : 程序包还原失败。正在回滚“05.Coldairarrow.Api”的程序包更改。
所在位置 行:1 字符: 1
+ Install-Package Masuit.Tools.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 `

系统环境  netcore  3.1.1

**Comment by ldqk** [comment]
目前项目所有的包引用都是安装到最新版的，提示检测到包降级可能是由于你项目中对应的这个包未升级到最新版。
