### ISSUE TITLE
请求添加新功能：能否添加标志位枚举获取Description

### ISSUE THREAD

**Issue by ArcherTrister** [ldqk/Masuit.Tools#102]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

请详细描述一下你想要的功能，实现什么效果？

```csharp
[Flags]
public enum MyEnum
{
    [Description("读")]
    Read=1,
  
    [Description("写")]
    Write=2,
}

MyEnum en = MyEnum.Read | MyEnum.Write;
var desc = en.GetDescription();
// desc => 读、写
```

**Comment by ldqk** [comment]
这个功能目前是已经有的，你可能用的是比较老版本的包，建议升级到最新版试试

**Comment by ArcherTrister** [comment]
@ldqk 感谢回复，之前尝试升级过，但是有些功能就没有了就回退了，比如进制转换（ToBinary、FromBinary），那我就在项目中添加吧，以后再考虑升级

**Comment by ldqk** [comment]
进制转换（ToBinary、FromBinary）后来改名了，叫ToBase、FromBase，如果某次升级发现有些功能报错了，建议在readme找一下最新用法就好啦

**Comment by ArcherTrister** [comment]
@ldqk 非常感谢，是我失误了，我正常看的是wiki，wiki上的没有更新，所以我以为是被删除了
![image](https://github.com/ldqk/Masuit.Tools/assets/35516482/438df799-d7b0-436a-8021-82fd5fa4121a)

**Comment by hjkl950217** [comment]
wiki可以更新下了。。只留下：查看readme文件。。233
