### ISSUE TITLE
请求添加新功能：增加密码生成/弱密码检测功能

### ISSUE THREAD

**Issue by NOBB2333** [ldqk/Masuit.Tools#103]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

请详细描述一下你想要的功能，实现什么效果？
希望增加密码生成的简易功能，根据用户输入的一个字符串作为标记，为不同的平台输出不同的加密密码，
```C#
public string genertPassWord( string enCryptCode):
{
...
return pasword
}
```
一般来说大家很容易忘记密码，我已经统计当前市面上的密码复杂度要求如下：
口令至少由8位及以上大写字母、小写字母、数字及特殊符号等4类中3类混合
不要以姓名、电话号码以及出生日期等作为口令或者口令的组成部分
口令应与用户名无相关性，口令中不得包含用户名的完整字符串、大小写变位或形似变换的字符串、反序字符串
口令设置禁止3位以上（含3位）键盘排序密码，如qwe、asd、qaz、1qaz、!QAZ等
口令设置禁止3位以上（含三位）连续字母、数字、特殊字符，如ABC、Abc、123、！@#等
口令设置禁止3位以上（含三位）重复字母、数字、特殊字符，如AAA、Aaa、111、###等
密码不能为帐号的反序，如root/toor等
严禁包含带公司名信息的字符“xxxxxxx”等 （根据个性化要求）

**Comment by ldqk** [comment]
弱密码检测的功能是已有的，ComplexPasswordAttribute就是强密码校验，强密码生成的行为可以考虑使用NumberFormater的91进制模式实现强密码生成

**Comment by ldqk** [comment]
强密码校验：
```csharp
public class MyClass
{
    [ComplexPassword]//密码复杂度校验，默认最小长度6，最大长度30，必须包含数字、字母、特殊符号
    public string Password { get; set; }
  
    [ComplexPassword(MustNumber=true,MustLetter=true,MustSymbol=true)]//密码复杂度校验，默认最小长度6，最大长度30，手动配置必须包含数字、字母、特殊符号
    public string Password2 { get; set; }
  
    [ComplexPassword(4,12)]//密码复杂度校验，配置最小长度4，最大长度12
    public string Password3 { get; set; }
}
```

生成12位长度的强密码：
```csharp
var pwd = Guid.NewGuid().ToString("N").FromBaseBig(16).ToBase(91)[..12];
```
![image](https://github.com/ldqk/Masuit.Tools/assets/20254980/1d0646b3-0c1a-429c-bdd3-28eb363a956f)
不同的进制对应了不同的符号：  
10进制：只包含数字  
36进制：包含数字和小写字母  
62进制：包含数字和大小写字母  
91进制：包含数字+大小写字母+可打印特殊符号  
所以可以通过NumberFormater来生成强密码，当然，FromBase和ToBase这种内置函数是固定的字符序列，如果你需要自定义字符序列，则需要显式调用NumberFormater构造函数传入你的自定义字符序列，并调用FromString和ToString函数去生成，如：只允许大小写+特殊符号：
```csharp
var num = Guid.NewGuid().ToString("N").FromBaseBig(16);
var formater = new NumberFormater("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ._-!~'*()@$#%+?&/\\,:;<=>?[]^`{|}\"");
var pwd = formater.ToString(num);
Console.WriteLine(pwd[..12]);
```
![image](https://github.com/ldqk/Masuit.Tools/assets/20254980/fd2b5028-9531-4f65-87a4-373012445137)

**Comment by NOBB2333** [comment]
找到了，`Masuit.Tools-master\Masuit.Tools.Abstractions\Validator\ComplexPassword.cs`在这有
考虑到密码严谨性，键盘连续三位检测能否考虑增加，这个可能有难度

我也看到了回复，发现一个问题，随即有随机好处，我也只是提一点想法，根据输入的 字符串，产生出 固定的 密码，这样保证输出的唯一性，同时符合密码的要求

**Comment by ldqk** [comment]
键盘连续三位检测不建议，正常情况下用户密码通常可能包含连续三位的键盘序列或者字母序列(即使不是特意使用连续三位，而是很多的英文单词本身就包含这种情况)，用户通常是为了考虑密码的易读性和安全性而特意这样设定的；
还有你说的非随机生成强密码，其实现有的函数也能做，比如crc32/64，MD5，SHAxxx后取前n位或者中间n位虽然生成出来的结果可能只有16进制或者62进制，但也能转换成10-91的任意进制，这都能保证输入和输出是稳定的

**Comment by NOBB2333** [comment]
懂了，多谢解惑， issue  关闭
