### ISSUE TITLE
[BUG] 检测mp4文件，会出现异常System.ArgumentOutOfRangeException: The Position must be within the length of the Stream: 2041547 (Parameter 'value')

### ISSUE THREAD

**Issue by aihui109** [ldqk/Masuit.Tools#104]
`温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！ ` 

**bug描述**
检测mp4文件，会出现异常

**是哪个类的哪个函数出现了bug？**
stream.DetectFiletype()

**异常堆栈信息**
 The Position must be within the length of the Stream: 2041547 (Parameter 'value')
Actual value was 469762048.
System.ArgumentOutOfRangeException: The Position must be within the length of the Stream: 2041547 (Parameter 'value')
Actual value was 469762048.
   at Microsoft.AspNetCore.Http.ReferenceReadStream.set_Position(Int64 value)
   at Masuit.Tools.Files.FileDetector.AbstractISOBaseMediaFileDetailDetector.Detect(Stream stream)
   at Masuit.Tools.Files.FileDetector.FileSignatureDetector.DetectFiletype(Stream stream)

**函数入参**
*.mp4文件测试

**期望的结果或输出**
无异常

**使用环境:**
 - OS: [CentOS ]
 - Version [7]
 - .NET Runtime [7.0]

**Comment by ldqk** [comment]
看起来你是通过文件上传的时候做文件类型检测，我写了一段示例代码，检测大于1GB的mp4视频文件是没问题的，不知道你遇到的这个错误是个别文件爆出来的还是所有文件都报这个错误？
如果可以的话，建议提供一份报错的mp4文件供我调试看看
![image](https://github.com/ldqk/Masuit.Tools/assets/20254980/61f4a57b-2be3-4242-a362-88bc540f12eb)
![image](https://github.com/ldqk/Masuit.Tools/assets/20254980/26531c00-621e-419c-8415-2f2abf29bf81)

**Comment by aihui109** [comment]
忘了说我用的版本是2.6.7.5.
https://github.com/ldqk/Masuit.Tools/assets/37268088/a5b6db41-5d35-4a8b-9266-b5d9e020d986

**Comment by aihui109** [comment]
不过可能跟我目前系统中用的abp vnext的IRemoteStreamContent类型接收file有关系也说不定。

**Comment by ldqk** [comment]
已修正，更新最新包即可。
