### ISSUE TITLE
[BUG]GetDaysOfMonth

### ISSUE THREAD

**Issue by 15937823** [ldqk/Masuit.Tools#106]
Masuit.Tools.Abstractions/DateTimeExt/DateTimeHelper.cs

/// <summary>本月有多少天</summary>
        /// <param name="now"></param>
        /// <returns>天数</returns>
        public static int GetDaysOfMonth(this DateTime now)
        {
            return now.**Year** switch
            {
                1 => 31,
                2 => DateTime.IsLeapYear(now.Year) ? 29 : 28,
                3 => 31,
                4 => 30,
                5 => 31,
                6 => 30,
                7 => 31,
                8 => 31,
                9 => 30,
                10 => 31,
                11 => 30,
                12 => 31,
                _ => 0
            };
        }

此处now.Year是不是应该是now.Month

**Comment by ldqk** [comment]
IsLeapYear判断是否是闰年，所以是now.Year

**Comment by 15937823** [comment]
return now.Year switch 是这个now.Year

**Comment by ldqk** [comment]
啊！您说的对

**Comment by ldqk** [comment]
已修正，更新最新包即可
