### ISSUE TITLE
RSA 使用私钥加密，公钥解密

### ISSUE THREAD

**Issue by MangMax** [ldqk/Masuit.Tools#107]
**Is your feature request related to a problem? Please describe.**
是否能添加RSA 签名方式使用私钥加密，公钥解密，用于让所有公钥所有者验证私钥所有者的身份并且用来防止私钥所有者发布的内容被篡改，但是不用来保证内容不被他人获得。

java的hutool有相关实现，不知是否也能支持一下

**Comment by ldqk** [comment]
能否给一个实际的案例，或者伪代码实现的效果
