### ISSUE TITLE
[咨询]: 是否有类似autoMapper的对象映射功能(例如2个不同类型的对象很多属性名一样,根据属性名自动映射值)

### ISSUE THREAD

**Issue by AlexScofield** [ldqk/Masuit.Tools#109]
### 您想讨论关于什么？

是否有类似autoMapper的对象映射功能(例如2个不同类型的对象很多属性名一样,根据属性名自动映射值)

**Comment by hjkl950217** [comment]
我记得库里是没有这个功能的，对应映射的话，automapper已经做的很好了

**Comment by AlexScofield** [comment]
> 我记得库里是没有这个功能的，对象映射的话，automapper已经做的很好了

要是能集成就好了.  或者反射做一个轻量级的相同属性名的自动拷贝.  实在不想引入太多的依赖了

**Comment by AlexScofield** [comment]
> 我记得库里是没有这个功能的，对象映射的话，automapper已经做的很好了

要是能集成就好了.  或者反射做一个轻量级的相同属性名的自动拷贝.  实在不想引入太多的依赖了

**Comment by hjkl950217** [comment]
以前有讨论过，这个功能看着简单，做起来很困难。。如果对性能不敏感的话推荐走json的方式。。先转成json字符串，再转成另一个类型。  中小规模，用这种方法又简单又没什么bug

**Comment by ldqk** [comment]
以前是有提供过类似autoMapper的映射功能的，但是很遗憾，功能很有限，鸡肋玩意儿，所以后续移除了该功能，还是使用正经的autoMapper吧

**Comment by quliting** [comment]
Mapster
