### ISSUE TITLE
.net stardand2.0支持

### ISSUE THREAD

**Issue by j4587698** [ldqk/Masuit.Tools#11]
没什么必要直接上到.net stardand 2.1吧？2.1直接就把.net framework抛弃掉了啊。
既然.net framework版本的已经到了4.6.1，为什么不直接做成.net stardand 2.0支持呢？这样更方便一点把？

**Comment by ldqk** [comment]
.net framework的项目应该引用不带Core后缀的nuget包，这个库针对Framework和Core版本分别定制的两套功能相同，但API设计是略有不同的，尤其是对MVC和EF的支持，都是区分对待的，不能统一成一个库，供Core和Framework统一引用。
