### ISSUE TITLE
[咨询]: Microsoft.EntityFrameworkCore2.2.6版本已弃用

### ISSUE THREAD

**Issue by yuezhishun** [ldqk/Masuit.Tools#110]
### 您想讨论关于什么？

项目Masuit.Tools.Core仍在引用，希望消除感叹号
```
    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="[2.2.6]" />
    </ItemGroup>
```

**Comment by ldqk** [comment]
这个是为了兼容低版本项目的，如果你的项目高于netstandard2.0，会自动引用对应版本的EntityFrameworkCore

**Comment by ldqk** [comment]
虽然3.1.32是符合netstandard2.0的，但是并不兼容netcoreapp2.2及以下版本的web项目，所以才将EntityFrameworkCore版本限定在netcoreapp的最高版本2.2.6

**Comment by ldqk** [comment]
如果可以的话，将你的类库项目升级为netstandard2.1的项目，就会自动引用3.1.32版本的EntityFrameworkCore了

**Comment by yuezhishun** [comment]
原来如此，感谢耐心解答
项目引用EntityFrameworkCore的3.1.32版本后可以自动覆盖2.2.6，正常运行，就是看到感叹号总想消除:)
