### ISSUE TITLE
[bug反馈]: 6.纳秒级性能计时器 纳秒时间换算的不对

### ISSUE THREAD

**Issue by hjfmailbox** [ldqk/Masuit.Tools#113]
### 版本号

latest (最新的)

### .NET SDK

.NET8

### 项目类型

Console

### 操作系统

Windows 11

### 运行环境

开发环境 (Development)

### 应用托管程序

Kestrel

### 如何复现

时间换算，秒s、毫秒ms、微秒μs、纳秒ns，相邻换算进制应该是1000，但是纳秒似乎不正确，如下面代码执行后，最后两行显示并不相同
```
        public static void TestTimer()
        {
            HiPerfTimer timer = HiPerfTimer.StartNew();
            Thread.Sleep(3000);
            timer.Stop();
            Console.WriteLine($"睡眠3s耗时:{timer.Duration:E6} s");
            Console.WriteLine($"睡眠3s耗时:{timer.Duration * 1000.0:E6} ms");
            Console.WriteLine($"睡眠3s耗时:{timer.Duration * 1000.0 * 1000.0:E6} μs");
            Console.WriteLine($"睡眠3s耗时:{timer.Duration * 1000.0 * 1000.0 * 1000.0:E6} ns");
            Console.WriteLine($"睡眠3s耗时:{timer.DurationNanoseconds:E6} ns");
        }
```

### 预期结果

睡眠3s耗时:3.002785E+000 s
睡眠3s耗时:3.002785E+003 ms
睡眠3s耗时:3.002785E+006 μs
睡眠3s耗时:3.002785E+009 ns
睡眠3s耗时:3.002785E+009 ns

### 实际结果

睡眠3s耗时:3.002785E+000 s
睡眠3s耗时:3.002785E+003 ms
睡眠3s耗时:3.002785E+006 μs
睡眠3s耗时:3.002785E+009 ns
睡眠3s耗时:3.002785E+007 ns

### 截图或视频

![image](https://github.com/ldqk/Masuit.Tools/assets/24580456/8601d304-8c44-41fe-9ad8-8dc7bb1b6e3b)

### Demo 地址（Git/网盘/SVN）

https://gist.github.com/hjfmailbox/1794d392182244e58ec87e53f40a137b#file-program-cs

**Comment by ldqk** [comment]
已修正，更新最新包即可
