### ISSUE TITLE
获取真实文件类型报错

### ISSUE THREAD

**Issue by XiwiNetwork** [ldqk/Masuit.Tools#117]
### 版本号

latest (最新的)

### .NET SDK

.NET Framework4.6.2+

### 项目类型

WinForm

### 操作系统

Windows 11

### 运行环境

开发环境 (Development)

### 应用托管程序

单文件

### 如何复现

**全代码如下：**
![全代码](https://github.com/user-attachments/assets/d9167b92-216d-4c86-bb00-4e39b7b1fa29)

**环境配置如下：**
VS：Microsoft Visual Studio Community 2022 (64 位) - Current   版本 17.10.5
Window：Windows 11 家庭中文版 23H2
NET：.NET Framework 4.6.2

### 预期结果

无

### 实际结果

![报错代码](https://github.com/user-attachments/assets/fba08e50-4be4-4a9c-84ea-bf26ce6926d7)

![运行日志](https://github.com/user-attachments/assets/9a5416fd-7cb0-446c-84d2-462b28ab2711)

### 截图或视频

**NoGet包依赖如下：**
![NoGet包依赖](https://github.com/user-attachments/assets/8c1a68c9-965f-4187-aadc-880fe4563f02)

### Demo 地址（Git/网盘/SVN）

无

**Comment by ldqk** [comment]
请提供一个可复现的最小demo，打包上传

**Comment by XiwiNetwork** [comment]
[Uploading test01.zip…]()

**Comment by XiwiNetwork** [comment]
[test01.zip](https://github.com/user-attachments/files/16541026/test01.zip)

**Comment by ldqk** [comment]
有点奇怪，Framework的特供版会报错，Abstraction的通用版不报错，如果不是需要用到特供版里面功能的话，建议先用Abstraction通用版的包吧

**Comment by XiwiNetwork** [comment]
Abstraction版安装失败。
demo还是上面的 test01.zip

**通过PM命令行报错如下：**
![PM命令行报错](https://github.com/user-attachments/assets/09918096-a7af-4181-ab66-4a4205b19e97)

**在NuGet包管理报错如下（只安装 AngleSharp.Css 版本为0.17.0）：**
![NuGet包管理报错](https://github.com/user-attachments/assets/f4f25299-0f05-4c10-be04-4bb669635e08)


**在NuGet包管理报错如下（有安装 AngleSharp.Css和AngleSharp 两个版本均0.17.0）：**
![NuGet包管理报错](https://github.com/user-attachments/assets/87dd205a-3a35-4e8a-8713-8b8ba82618ab)

**NuGet包管理报错如下（在安装 AngleSharp.Css 版本为0.17.0 情况下在安装AngleSharp版本1.1.2）：**
![NuGet包管理报错](https://github.com/user-attachments/assets/863c1967-75f5-4bf7-8dc5-38f4c58df9d9)


**NuGet包源配置如下：**
![NuGet包源配置](https://github.com/user-attachments/assets/86bd7e11-b735-43c7-82fb-82074b3f1301)




**Abstraction版 依赖 AngleSharp(>= 1.1.2)和AngleSharp.Css(>= 1.0.0-beta.139)** 
**但AngleSharp.Css最高只有0.17 且规定约束 AngleSharp(>= 0.17.0 && <0.18.0)**  
**这个明显也不符合Abstraction版的依赖规定，作者用的是NuGet包源是默认的吗？还是用的另外其它的包源？**

**Comment by XiwiNetwork** [comment]
上诉我尝试安装 Net版 是可以安装成功， Abstraction版就不可以

**Comment by XiwiNetwork** [comment]
**附上Nuget包管理 AngleSharp.Css 依赖界面：**
![Nuget包管理 AngleSharp.Css 依赖界面](https://github.com/user-attachments/assets/579e08d8-2595-4678-b3b6-3662dbae0d33)

![image](https://github.com/user-attachments/assets/77839c50-97d2-45ef-8eac-f53ce69ca53a)


我这边 AngleSharp.Css 最高版本 0.17.0，是不是包源不同 我这边拿到的依赖版本也有所差异？

**Comment by ldqk** [comment]
将AngleSharp相关包卸载后再安装Masuit.Tools.Abstraction包吧

**Comment by ldqk** [comment]
另外，Framework项目建议使用PackageReference的方式引用包，保持包依赖的纯净

**Comment by XiwiNetwork** [comment]
OKOK，感谢。关于AngleSharp.Css版本的问题我这边找到解决方案了。原因是Nuget似乎只显示稳定版 而AngleSparp.Css需要的是预发布版。我直接在nuget源包网站上找到对应的预发布版本的AngleSparp.Css通过PM命令导入了

![image](https://github.com/user-attachments/assets/eae50044-25d4-47b3-8173-30630ba2aa05)



[https://www.nuget.org/packages/AngleSharp.Css/1.0.0-beta.139#dependencies-body-tab](https://www.nuget.org/packages/AngleSharp.Css/1.0.0-beta.139#dependencies-body-tab)

**Comment by ldqk** [comment]
排查了一番发现是Framework版本的包在打包的时候没有把相关依赖项打包进去，重新更新最新包即可
