### ISSUE TITLE
[bug反馈]: .netframewok，提	找不到与 'Masuit.Tools.Abstractions 2024.5.2 约束: AngleSharp.Css (>= 1.0.0-beta.139)' 兼容的“AngleSharp.Css”版本。					

### ISSUE THREAD

**Issue by hsfzmsn** [ldqk/Masuit.Tools#118]
### 版本号

latest (最新的)

### .NET SDK

.NET Framework4.6.2+

### 项目类型

WinForm

### 操作系统

Windows 10

### 运行环境

开发环境 (Development)

### 应用托管程序

单文件

### 如何复现

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误		找不到与 'Masuit.Tools.Abstractions 2024.5.2 约束: AngleSharp.Css (>= 1.0.0-beta.139)' 兼容的“AngleSharp.Css”版本。					
2024.5.0以上版本不行

### 预期结果

装不上

### 实际结果

装不上

### 截图或视频

![微信截图_20240814110810](https://github.com/user-attachments/assets/e76c62c3-c2be-4e20-b33f-f70f2907bce7)

### Demo 地址（Git/网盘/SVN）

无

**Comment by ldqk** [comment]
勾选包含预发行版，然后尝试搜索AngleSharp.Css，看是否能找到1.0.0-beta.139的包

**Comment by ldqk** [comment]
nuget官网是能找到这个包的，https://www.nuget.org/packages/AngleSharp.Css/1.0.0-beta.139

**Comment by hsfzmsn** [comment]
勾选包含预发行版，直接安装不行，手动的先安装AngleSharp.Css 1.0.0-beta.139，就可以了

**Comment by hsfzmsn** [comment]
勾选包含预发行版，直接安装不行，手动的先安装AngleSharp.Css 1.0.0-beta.139，就可以了
