### ISSUE TITLE
获取真实文件类型报错···············

### ISSUE THREAD

**Issue by quliting** [ldqk/Masuit.Tools#119]
### 版本号

latest (最新的)

### .NET SDK

.NET8

### 项目类型

Console

### 操作系统

Windows 11

### 运行环境

开发环境 (Development)

### 应用托管程序

Kestrel

### 如何复现

下载Demo，解压，F5

### 预期结果

识别到，这个是doc

### 实际结果

![image](https://github.com/user-attachments/assets/77f0cb62-f1c4-485f-b252-44f578562e47)

### 异常信息

不支持的文件格式，请自己实现针对该文件的IDetector

### 截图或视频

报错

### Demo 地址（Git/网盘/SVN）

https://drive.weixin.qq.com/s?k=AG8AkgfSABoE0Y4izw

**Comment by ldqk** [comment]
企业微信网盘，demo下载不了

**Comment by quliting** [comment]
> 企业微信网盘，demo下载不了

https://quliting.lanzouv.com/i5NDR27hvpjc

**Comment by ldqk** [comment]
doc文件没支持，等下期更新吧，或者自己先实现一个DocDectector

**Comment by quliting** [comment]
> doc文件没支持，等下期更新吧，或者自己先实现一个DocDectector

感谢；
