### ISSUE TITLE
.NET Framework 版本能否降低一点？

### ISSUE THREAD

**Issue by Assur** [ldqk/Masuit.Tools#12]
很多项目都是.NET Framework  4.5的，能否降低版本？

**Comment by ldqk** [comment]
这就不行了，因为其中引用的有好几个类库都是要求≥4.6.1的，所以项目只能基于4.6.1进行发布，其中包含HTML处理以及文件（解）压缩的依赖库是4.6.1的，如果你项目中用不到这两大块的功能，可以将其依赖卸载并移除这部分代码后降级项目重新打包，或直接摘取本项目中你需要的代码进行直接使用。
