### ISSUE TITLE
[bug反馈]: ini文件写入时value特殊值丢失

### ISSUE THREAD

**Issue by Schreber** [ldqk/Masuit.Tools#120]
### 版本号

latest (最新的)

### .NET SDK

.NET8

### 项目类型

Console

### 操作系统

Windows 11

### 运行环境

开发环境 (Development)

### 应用托管程序

单文件

### 如何复现

1. 创建 IniFile 对象，写入一个带"="的值，然后保存。
2. 模拟应用打开，再次创建这个ini文件的对象，再写入其他值，那么第一次写入的值"="后面的值会被删除掉

### 预期结果

保留住"="及其他特殊字符，这里由于等号是特殊字符，所以我觉得应该采用转义的方式写入

### 实际结果

按照源码，value值根据"="分隔，并只取了等号左侧的值

### 截图或视频

![image](https://github.com/user-attachments/assets/9345c8af-8269-4669-b907-11ddbf5de115)

### Demo 地址（Git/网盘/SVN）

https://dotnetfiddle.net/mht0pL

**Comment by ldqk** [comment]
已修正，更新最新包即可
