### ISSUE TITLE
Linux平台下RSA加密出现问题

### ISSUE THREAD

**Issue by YAGAMIL** [ldqk/Masuit.Tools#18]
Windows平台下没有问题
服务版本：ASP.Net Core2.1
Masuit.Tools版本

Masuit.Tools.NET 2.2.9.1

windows平台下正常
Linux环境下：
异常信息：
An unhandled exception has occurred while executing the request.
System.PlatformNotSupportedException: 'CspParameters' requires Windows Cryptographic API (CAPI), which is not available on this platform.
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
   at Masuit.Tools.Security.RsaPem.GetRSA()
   at Masuit.Tools.Security.RSA..ctor(String key)

**Comment by hjkl950217** [comment]
插眼

**Comment by ldqk** [comment]
感谢反馈，问题已修正，请更新2.2.9.2版本。

**Comment by YAGAMIL** [comment]
> 感谢反馈，问题已修正，请更新2.2.9.2版本。

已更新，问题已经解决，我原本做java的，算是C#初学者，我看了你的源码觉得非常优秀，RSA加密那个官方不建议用RSAParam了我记得好像，但是我自己继承了你的RSA类尝试用你的方式实现，结果放弃了，自己重写了RSA加密，我想看看你的源码改动，是如何做到兼容更新的，非常感谢

**Comment by ldqk** [comment]
> > 感谢反馈，问题已修正，请更新2.2.9.2版本。
> 
> 已更新，问题已经解决，我原本做java的，算是C#初学者，我看了你的源码觉得非常优秀，RSA加密那个官方不建议用RSAParam了我记得好像，但是我自己继承了你的RSA类尝试用你的方式实现，结果放弃了，自己重写了RSA加密，我想看看你的源码改动，是如何做到兼容更新的，非常感谢

其实是CspParameters是在Windows下的专用的加密方法，而在Windows下该类对加密是可有可无的，导致在Linux下报不支持的异常。

**Comment by YAGAMIL** [comment]
> > > 感谢反馈，问题已修正，请更新2.2.9.2版本。
> > 
> > 
> > 已更新，问题已经解决，我原本做java的，算是C#初学者，我看了你的源码觉得非常优秀，RSA加密那个官方不建议用RSAParam了我记得好像，但是我自己继承了你的RSA类尝试用你的方式实现，结果放弃了，自己重写了RSA加密，我想看看你的源码改动，是如何做到兼容更新的，非常感谢
> 
> 其实是CspParameters是在Windows下的专用的加密方法，而在Windows下该类对加密是可有可无的，导致在Linux下报不支持的异常。

这个我知道，我看你代码抽象的非常不错，但没想出来怎么在你的体系里更换加密方法
