### ISSUE TITLE
支持netstandard 2.0 

### ISSUE THREAD

**Issue by mindfocus** [ldqk/Masuit.Tools#2]
能否去除System.Drawing引用及相关图片处理库，然后支持netstandard2.0?

**Comment by mindfocus** [comment]
目前看起来 Masuit.Tools.Core 依赖项为.NETCoreApp 不太合理

**Comment by ldqk** [comment]
其实包里太多用到了.NETCoreApp的API，用netstandard2.0不行，得去除这些依赖的东西才行

**Comment by ldqk** [comment]
如果你只使用库里的部分功能，我完全不建议你安装nuget，你可以自己down下代码去编译你需要的那一部分代码就好了

**Comment by mindfocus** [comment]
好的 谢谢
 正在弄一些这边的代码 如果有进展 会提个pr
