### ISSUE TITLE
在Blog.core框架中通过nuget安装Masuit.Tool后，启动项目在UseEndpoint时候出现以下错误

### ISSUE THREAD

**Issue by inows** [ldqk/Masuit.Tools#27]
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.AspNetCore.Mvc.Infrastructure.IActionDescriptorCollectionProvider, Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory)' on type 'ControllerActionEndpointDataSource'.

ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Masuit.Tools.Abstractions, Version=2.3.1.5, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'Masuit.Tools.Abstractions, Version=2.3.1.5, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'Masuit.Tools.Abstractions, Version=2.3.1.5, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'Masuit.Tools.Abstractions, Version=2.3.1.5, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。

请问这种应该如何定位 谢谢

**Comment by inows** [comment]
![image](https://user-images.githubusercontent.com/15324558/93407596-274fac00-f8c5-11ea-9ae6-7a870ba1c53c.png)
我直接新建个空core项目 nuget安装Masuit并未做任何引用，也出现了类似问题

**Comment by hjkl950217** [comment]
试试这个：删除 `C:\Users\｛你的用户名｝\.nuget\packages`下面的全部nuget包缓存文件，然后项目中也清理一下， 然后重新生成试试

**Comment by inows** [comment]
经测试，在nuget市场，最新能用的版本是2.3.1.1,往后的版本都存在这种问题，初步推测应该是打包依赖没搞好

**Comment by inows** [comment]
问题找到了  就此结题吧
