### ISSUE TITLE
项目在Nuget中安装Masuit Tool后运行出现Masuit.Tool.Abstractions 特定版本dll不存在的问题

### ISSUE THREAD

**Issue by inows** [ldqk/Masuit.Tools#28]
项目在Nuget中安装Masuit Tool后运行出现Masuit.Tool.Abstractions 特定版本dll不存在的问题，此问题出现在2.3.1.11以后版本，估计是打包漏了2.3.1.12版本导致的依赖文件版本错乱，希望修复此问题

**Comment by hjkl950217** [comment]
#27

**Comment by inows** [comment]
> #27

这个问题没有实质性解决，回退版本只是权宜之计，所以还是打算重新开个issue来给大佬贴个提醒，希望有空的时候修复一下，避免小白踩坑无头绪

**Comment by ldqk** [comment]
是安装的Core版本的包还是Framework版本的包？

**Comment by inows** [comment]
> 是安装的Core版本的包还是Framework版本的包？

是Masuit.Tools.Core

**Comment by ldqk** [comment]
重新打包发布了Masuit.Tools.Core 2.3.1.6-preview预览版，安装试试看？

**Comment by inows** [comment]
> 重新打包发布了Masuit.Tools.Core 2.3.1.6-preview预览版，安装试试看？

Masuit.Tools.Core 2.3.1.6-preview  可用，已测试

**Comment by ldqk** [comment]
Masuit.Tools.Core 2.3.1.6已重新打包上传

**Comment by inows** [comment]
> Masuit.Tools.Core 2.3.1.6已重新打包上传

谢谢大佬解决
