### ISSUE TITLE
MDString 扩展方法部分结果与标准算法结果不同。

### ISSUE THREAD

**Issue by OAngs** [ldqk/Masuit.Tools#42]
加密前字符串：
amount=1.42857&bcode=USDT&merchantno=20201012000008&merchantorder=202010251625581054138&notifyurl=http://api.fh356.com/notify/payment/usdt/&remark=&key=D822E01CCBABEF3250786A707D3C11D4
MDString 结果：d192c3ff878adb3bdcc894975a03e401
标准MD5 结果：4578bf8030dfccf7acaead570c1d97b7

**Comment by ldqk** [comment]
感谢反馈，已修正，请更新最新版本包
