### ISSUE TITLE
请教大佬个问题

### ISSUE THREAD

**Issue by jyh583854536** [ldqk/Masuit.Tools#43]
RSA 能私钥加密 公钥解密吗

**Comment by ldqk** [comment]
非对称加密的原理约定的是公钥加密，私钥解密，具体可以看下这篇文章的解释：https://masuit.com/1205

**Comment by jyh583854536** [comment]
多谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "懒得勤快"<notifications@github.com&gt;; 
发送时间: 2020年11月18日(星期三) 上午10:56
收件人: "ldqk/Masuit.Tools"<Masuit.Tools@noreply.github.com&gt;; 
抄送: "沧海一滴"<583854536@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ldqk/Masuit.Tools] 请教大佬个问题 (#43)





 
非对称加密的原理约定的是公钥加密，私钥解密，具体可以看下这篇文章的解释：https://masuit.com/1205
