### ISSUE TITLE
DateTime扩展缺少时间戳转换为时间的方法

### ISSUE THREAD

**Issue by ihambert** [ldqk/Masuit.Tools#46]
DateTime扩展里有时间转为各种时间戳的方法，但是貌似缺乏反向转换的方法

**Comment by ldqk** [comment]
是时间戳转换成DateTime类型吗？

**Comment by ihambert** [comment]
是的

**Comment by hjkl950217** [comment]
@ldqk  https://github.com/hjkl950217/learningTest/blob/3.1.0.14-FP/CkTools/Src/CkTools.BaseExtensions/Helper/TypeConvertDelegate.cs

各种版本

**Comment by ldqk** [comment]
这个不需要封装啊，.net自带的DateTimeOffset里面直接有时间戳转datetime的函数

**Comment by ldqk** [comment]
> @ldqk https://github.com/hjkl950217/learningTest/blob/3.1.0.14-FP/CkTools/Src/CkTools.BaseExtensions/Helper/TypeConvertDelegate.cs
> 
> 各种版本【斜眼笑】，要不你搬运一波？

你这个看起来太复杂了，直接用DateTimeOffset一句话的事情

**Comment by hjkl950217** [comment]
> > @ldqk https://github.com/hjkl950217/learningTest/blob/3.1.0.14-FP/CkTools/Src/CkTools.BaseExtensions/Helper/TypeConvertDelegate.cs
> > 各种版本【斜眼笑】，要不你搬运一波？
> 
> 你这个看起来太复杂了，直接用DateTimeOffset一句话的事情

看情况吧。我那里是因为有各种情况要处理，为了方便就拆分成不同的委托，用的时候组合起来了

**Comment by ldqk** [comment]
> 是的

![image](https://user-images.githubusercontent.com/20254980/102328805-71f1ca80-3f7f-11eb-8477-2888993bf7aa.png)

**Comment by ldqk** [comment]
> > > @ldqk https://github.com/hjkl950217/learningTest/blob/3.1.0.14-FP/CkTools/Src/CkTools.BaseExtensions/Helper/TypeConvertDelegate.cs
> > > 各种版本【斜眼笑】，要不你搬运一波？
> > 
> > 
> > 你这个看起来太复杂了，直接用DateTimeOffset一句话的事情
> 
> 看情况吧。我那里是因为有各种情况要处理，为了方便就拆分成不同的委托，用的时候组合起来了。
> 
> 我那边是在 DateTimeOffset 上有扩展，然后要考虑时区。 最开始是想用string->long->DateTimeOffset 一键自动化

DateTimeOffset本身就是带有时区功能的，想用哪个都是可以直接获取的

**Comment by ihambert** [comment]
那为啥DateTimeOffset不干脆把DateTime转时间戳也实现了

**Comment by hjkl950217** [comment]
> > > > @ldqk https://github.com/hjkl950217/learningTest/blob/3.1.0.14-FP/CkTools/Src/CkTools.BaseExtensions/Helper/TypeConvertDelegate.cs
> > > > 各种版本【斜眼笑】，要不你搬运一波？
> > > 
> > > 
> > > 你这个看起来太复杂了，直接用DateTimeOffset一句话的事情
> > 
> > 
> > 看情况吧。我那里是因为有各种情况要处理，为了方便就拆分成不同的委托，用的时候组合起来了。
> > 我那边是在 DateTimeOffset 上有扩展，然后要考虑时区。 最开始是想用string->long->DateTimeOffset 一键自动化
> 
> DateTimeOffset本身就是带有时区功能的，想用哪个都是可以直接获取的

DateTimeOffset是没有问题的，但是我收到的是"1608110649"这种， 不太好判断到底是什么时区，那次项目中。 一个接口加了时区偏移，一个没有加时区偏移，传递的都是“1608110649”这种， 才衍化了这么复杂的代码。  用的时候现在比较方便：
```
"1608110649".TryToLocalDatetimeOffset();
"1608110649".TryToUtcDatetimeOffset()
```

**Comment by ihambert** [comment]
正规的时间戳都是用的UTC时间吧

**Comment by ldqk** [comment]
> 那为啥DateTimeOffset不干脆把DateTime转时间戳也实现了

DateTimeOffset是有这个功能的，但是DateTime没有啊🤣🤣🤣，反着来的话是因为DateTimeOffset能够拿到DateTime对象啊

**Comment by ldqk** [comment]
> > > > > @ldqk https://github.com/hjkl950217/learningTest/blob/3.1.0.14-FP/CkTools/Src/CkTools.BaseExtensions/Helper/TypeConvertDelegate.cs
> > > > > 各种版本【斜眼笑】，要不你搬运一波？
> > > > 
> > > > 
> > > > 你这个看起来太复杂了，直接用DateTimeOffset一句话的事情
> > > 
> > > 
> > > 看情况吧。我那里是因为有各种情况要处理，为了方便就拆分成不同的委托，用的时候组合起来了。
> > > 我那边是在 DateTimeOffset 上有扩展，然后要考虑时区。 最开始是想用string->long->DateTimeOffset 一键自动化
> > 
> > 
> > DateTimeOffset本身就是带有时区功能的，想用哪个都是可以直接获取的
> 
> DateTimeOffset是没有问题的，但是我收到的是"1608110649"这种， 不太好判断到底是什么时区，那次项目中。 一个接口加了时区偏移，一个没有加时区偏移，传递的都是“1608110649”这种， 才衍化了这么复杂的代码。 用的时候现在比较方便：
> 
> ```
> "1608110649".TryToLocalDatetimeOffset();
> "1608110649".TryToUtcDatetimeOffset()
> ```

时间戳不都是相对于UTC的么

**Comment by hjkl950217** [comment]
@ldqk @ihambert 正常的是这样的。。但是有些坑货就是不懂，要传递添加了偏移的时间戳。。。

**Comment by ihambert** [comment]
php、java、python、ruby都提供了时间戳和时间的互相转换方法，是不是可以建议微软也提供一下自带的时间转时间戳方法

**Comment by ldqk** [comment]
人家是有提供的，只是互转稍微绕了一下，没那么直接🤣🤣

**Comment by hjkl950217** [comment]
> php、java、python、ruby都提供了时间戳和时间的互相转换方法，是不是可以建议微软也提供一下自带的时间转时间戳方法

如下:
```
            DateTimeOffset.Now.ToUnixTimeSeconds();
            DateTimeOffset.FromUnixTimeSeconds();
```

DateTime没有相关的可能是以前早期设计时，没有这么设计而已，基本上DateTime的API都没有修改过。 而新的`DateTimeOffset`已经相当完善了

**Comment by ihambert** [comment]
> > php、java、python、ruby都提供了时间戳和时间的互相转换方法，是不是可以建议微软也提供一下自带的时间转时间戳方法
> 
> 如下:
> 
> ```
>             DateTimeOffset.Now.ToUnixTimeSeconds();
>             DateTimeOffset.FromUnixTimeSeconds();
> ```
> 
> DateTime没有相关的可能是以前早期设计时，没有这么设计而已，基本上DateTime的API都没有修改过。 而新的`DateTimeOffset`已经相当完善了

原来已经有了，是我孤陋寡闻了，，，
