### ISSUE TITLE
websocket 支持

### ISSUE THREAD

**Issue by CharlieJ0hn** [ldqk/Masuit.Tools#48]
请求websocket支持

**Comment by ldqk** [comment]
不知道你是否有了解过SignalR和Blazor这两项技术，它们已经是websocket的高度封装了，开箱即用的。

**Comment by CharlieJ0hn** [comment]
主要是我这里没有没有用到 asp.net 相关的东西

**Comment by hjkl950217** [comment]
emm  websocket一般也是和web项目走的，如果是其它项目，一般是自己开socket哒

**Comment by ldqk** [comment]
那你可以考虑使用SignalR，它有相应的服务端和客户端库可供调用，如果不是web项目，你可以考虑rpc或者其他专门的socket库，这可能是你更好的选择

**Comment by CharlieJ0hn** [comment]
我这里是这样子，我们后端是java写的，他是给前端推送websocket消息，但是我现在要用到打印机，这个打印机给的sdk是c#的，所以只能用c#写个打印机驱动，这个驱动要接收后端给的消息并且打印出来，所以我就在c#的打印机程序里边直接监听了websocket

**Comment by hjkl950217** [comment]
噗呲。。那你不如直接开一个webapi项目，然后api里面去打印,还不用考虑连接稳定性

**Comment by CharlieJ0hn** [comment]
这个不现实，打印机在用户的电脑上，普通家用宽带能连上我的服务器，但是我连不上他的电脑，所以只能他监听我，不能我去访问他的webapi

**Comment by CharlieJ0hn** [comment]
如果大家都接入了公网，我直接给他们每个电脑开webapi，post过来就打印多舒服。问题就是没有。

**Comment by ldqk** [comment]
那你其实可以去找单独专门的C#的websocket客户端库，gayhub或者nuget也是上一搜一大把的

**Comment by CharlieJ0hn** [comment]
我现在用的是官方的 net.websocket

**Comment by ldqk** [comment]
![image](https://user-images.githubusercontent.com/20254980/103268351-31e10d80-49ab-11eb-8c41-3931527fa56a.png)

**Comment by CharlieJ0hn** [comment]
![image](https://user-images.githubusercontent.com/9925064/103268391-50b4c380-49ee-11eb-8be9-82730e29136c.png)
本来用这个的，常年不更新，不敢用了，换掉了。
