### ISSUE TITLE
依赖ASP.NET Core Mvc而无法被Blazor直接或间接引用

### ISSUE THREAD

**Issue by nidbCN** [ldqk/Masuit.Tools#49]
当Blazor项目安装包Masuit.Tools或其引用的项目（比如某些共享的模型）安装了Masuit.Tools时，编译器会报错：
```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Microsoft.AspNetCore.Mvc.ApplicationParts”中不存在类型或命名空间名“ApplicationPartAttribute”(是否缺少程序集引用?)	DotBlog.Blazor	xxxx\obj\Debug\net5.0\xxxx.MvcApplicationPartsAssemblyInfo.cs	14	活动

```
（这个报错挺迷惑的，因为它报错的文件是MSbuild自动生成的）
原因是**Blazor不支持使用ASP.NET Core Mvc的二进制库**[相关issue链接](https://github.com/dotnet/aspnetcore/issues/27373)，而Masuit.Tools依赖中有ASP.NET Core Mvc。
我不知道能否不依赖于ASP.NET Core Mvc。为了防止后来者踩坑就发个issue
（说实话Blazor不能用Masuit.Tools挺难受的，毕竟很难找到和这个媲美的工具库）

**Comment by ldqk** [comment]
如果你不需要用到ASP.NET Core Mvc的相关功能，其实你只需要引用Masuit.Tools.Abstraction这个包就好了

**Comment by ldqk** [comment]
Masuit.Tools.Abstraction提供的是一些标准库的扩展功能，而Masuit.Tools.Core是基于Masuit.Tools.Abstraction的功能上，还提供了MVC的相关功能扩展
