### ISSUE TITLE
能否支持List分割扩展

### ISSUE THREAD

**Issue by yzpopulation** [ldqk/Masuit.Tools#50]
能否支持IEnumerable分割扩展？
1.如有个List 有 200000 元素 要平均分成 5个list
2.如有个List 有 200000 元素 分成每个List 1000个（主要用于数据库录入数据时，一次太多影响拼接性能，需要分割）

建议代码如下，可能抄写的不是很好，也是百度的
1.
splitlist<T>(this list<T> src,int nsize){
for (int i=0;i<src.count;i+=nsize){
yield return src.getrange(i,math.min(nsize,src.count-i));
}
}
2.
chucklist<T> (this list<T> src,int nsize){
int count=src.count/nsize;
if (src.count % nsize !=0){
count++;
}
for (int i=0;i<nsize;i++){
if (i==nsize-1){
yield return src.getrange(i*count,src.count-i*count);
}else{
yield return src.getrange(i*count,count);
}
}
}

**Comment by hjkl950217** [comment]
需求+1！
不过你百度的这个代码。。全小写哎。。

`List<T>`和`IEnumerable<T>`是不同的类型的。`List<T>`知道数量，取余或是用skip taik去做都可以。。但是`IEnumerable`是不知道数量的。

**Comment by ldqk** [comment]
这种需求我的建议是直接用linq的分组或者分页函数就可以了，比如20w个元素按1k个元素分：
``` csharp
var groups=sourceList.Select((item,index)=>(item,index)).GroupBy(t=>t.index/1000);
```
这样得到的结果就是每组1000条数据的集合

**Comment by hjkl950217** [comment]
封装linq方法的组合算不算封装233

**Comment by yzpopulation** [comment]
基础比较薄弱，比如20w个元素分成66组 的能加个扩展吗

**Comment by yzpopulation** [comment]
另外字符串转时间扩展能不能多支持一点种类，写的不好下面

``` 
public static DateTime ToDateTime(this string value)
        {
            DateTime.TryParse(value, out var result);
            if (result.Year == 1)
            {
                try
                {
                    result = DateTime.ParseExact(value, "yyyyMMddHHmmss", CultureInfo.InvariantCulture);
                    return result;
                }
                catch
                {
                    
                }
                try
                {
                    result = DateTime.ParseExact(value, "yyyyMMdd", CultureInfo.InvariantCulture);
                    return result;
                }
                catch
                {
                }
            } 
            return result;
        }
```

**Comment by hjkl950217** [comment]
字符串转时间扩展这个自己写吧，你用的是精确转换。用DateTime.Parse 就可以了

**Comment by yzpopulation** [comment]
扩展包太多了，想整合一下，引用太多，集中一个最好

**Comment by hjkl950217** [comment]
@yzpopulation 转时间这个就自己在项目里写吧，库里的转时间我看了下没有问题，只要你的源数据没问题就好了，这里也不应该通过try去处理的。

**Comment by yzpopulation** [comment]
业务里也不用try?

**Comment by hjkl950217** [comment]
你贴的代码肯定不是库里的。库里的是这样:
```
     public static DateTime ToDateTime(this string value)   
    {           
         DateTime.TryParse(value, out var result);       
     return result;    
    }
```

转换失败返回的是DateTime的默认值。

我的意思是这里不能通过try去鉴别用什么转换字符串，用兼容模式转换就行了。 DateTime.Parse是兼容模式，DateTime.ParseExact是精确模式

**Comment by yzpopulation** [comment]
Parse 不支持 format
@hjkl950217 大神 写个 pull request 吧，分割扩展加进去

**Comment by hjkl950217** [comment]
parse不需要format的呀

**Comment by yzpopulation** [comment]
![image](https://user-images.githubusercontent.com/12810531/118800672-c43e6b00-b8d2-11eb-8f91-895f5d474f91.png)

**Comment by ldqk** [comment]
这种DateTime类本身就是支持自定义格式化转换的，没必要封装，封装了反而不那么灵活，并且写代码的时候IDE没有格式字符串的智能提示

**Comment by ldqk** [comment]
> 基础比较薄弱，比如20w个元素分成66组 的能加个扩展吗

这种也直接分组或分页啊，linq很灵活很方便，20w个分66组一样的按Index/(20w/66)进行分组就好了啊，如果你觉得groupby分组后顺序会乱，那就考虑分页的形式
