### ISSUE TITLE
直接报错，语法没法通过

### ISSUE THREAD

**Issue by aion1998** [ldqk/Masuit.Tools#52]
![image](https://user-images.githubusercontent.com/19725014/124697678-cbb8e280-df19-11eb-8eec-3f01b19293c0.png)

什么都没改，代码也是示例中复制的

**Comment by ldqk** [comment]
SevenZipCompressor的静态调用只能在.NET Framework中使用，.NET Core/.NET Standard/.NET5中需要实例化后再使用

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/124700006-81863000-df1e-11eb-97c3-a1736e413c82.png)

大意了，感谢，可以了
