### ISSUE TITLE
搞个timespan转时间戳噻

### ISSUE THREAD

**Issue by aion1998** [ldqk/Masuit.Tools#53]
..就是有的时候时间相减，然后timespan需要转成时间戳返回前端

**Comment by ldqk** [comment]
这个操作，框架是自带支持的，datetime和timespan都是支持加减操作的

**Comment by aion1998** [comment]
..不是
我的意思是Timespan类型转时间戳
两个datetime加减的结果是timespan，然后这个timespan俺想转时间戳

**Comment by ldqk** [comment]
timespan有个TotalMilliseconds属性就是时间戳啊

**Comment by hjkl950217** [comment]
@aion1998  这种情况不应该返回时间戳。 2个datetime相减后得到的时间片段长度，但时间戳的定义为从格林威治时间1970年01月01日00时00分00秒起至现在的总秒数。  这俩之间不应该互相转吧？

**Comment by hjkl950217** [comment]
如果只是想要一个数字，那么用 @ldqk 说的方法直接拿到就可以了

**Comment by aion1998** [comment]
好吧，谢谢哈
