### ISSUE TITLE
俺又来了，这次是MultiThreadDownloader的问题

### ISSUE THREAD

**Issue by aion1998** [ldqk/Masuit.Tools#54]
![image](https://user-images.githubusercontent.com/19725014/125907163-86de8f61-b341-4f10-be03-f0a4fa8f17da.png)

我调试发现好像并不会等待着结束执行，会直接执行后面返回

但是实际上进程又被卡在里面，导致请求这个api的客户端一直等待最终超时

**Comment by aion1998** [comment]
主要实现的..很简单，下载完成然后上传图片到微信素材库

**Comment by hjkl950217** [comment]
看了下文档有个:
```
mtd.FileMergeProgressChanged+=(sender, e) =>
{
    Console.WriteLine("下载完成");
};
```

你可能要等这个事件触发时才能返回，代表上传完成了

**Comment by ldqk** [comment]
你最好是先阅读readme并拷贝示例代码跑一遍体验一下再用于你的生产代码。  
MultiThreadDownloader是基于事件模型实现的，Start并不是一个阻塞操作，只是触发开始下载的事件，如果你要等待下载完成，请务必使用文件合并完成事件FileMergedComplete去通知你的业务代码继续执行。

**Comment by aion1998** [comment]
有没有直接下载的鸭，俺这几百kb的图片也算不上大文件，只不过我找不到简单的下载所以才用这个

**Comment by ldqk** [comment]
小文件直接用httpclient的GetStreamAsync函数即可，MultiThreadDownloader这种重量级的下载方式更适合于上百MB的文件下载

**Comment by aion1998** [comment]
呜呜呜，那又要自己写一堆东西。。。。封装一个嘛，作者大大

**Comment by ldqk** [comment]
......，httpclient.GetStreamAsync就是官方最好的封装啊

**Comment by aion1998** [comment]
呜呜呜，谢谢了哈
