### ISSUE TITLE
StrictNext不安全

### ISSUE THREAD

**Issue by hyfree** [ldqk/Masuit.Tools#56]
# 函数原型

```
  /// <summary>
  /// 生成真正的随机数
  /// </summary>
  /// <param name="r"></param>
  /// <param name="seed"></param>
  /// <returns></returns>
  public static int StrictNext(this Random r, int seed = int.MaxValue)
  {
      return new Random((int)Stopwatch.GetTimestamp()).Next(seed);
  }
```
# 错误原因

Random((int)Stopwatch.GetTimestamp()).Next(seed)依赖于生成随机数的时间，也就是(int)Stopwatch.GetTimestamp()，如果我知道你生成的时间，那么我就可以猜测你产生的随机数。

因此这个方法是不安全的，不应该用于加密密钥和保护敏感信息的盐。

如果，您希望产生一个不可预测的安全随机数，应该使用`RNGCryptoServiceProvider`。system.Security.Cryptography.RNGCryptoServiceProvider的类，它采用系统当前的硬件信息、进程信息、线程信息、系统启动时间和当前精确时间作为填充因子，通过更好的算法生成高质量的随机数

https://docs.microsoft.com/zh-cn/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?view=net-5.0#code-try-3

```C#
//The following sample uses the Cryptography class to simulate the roll of a dice.

using System;
using System.IO;
using System.Text;
using System.Security.Cryptography;

class RNGCSP
{
    private static RNGCryptoServiceProvider rngCsp = new RNGCryptoServiceProvider();
    // Main method.
    public static void Main()
    {
        const int totalRolls = 25000;
        int[] results = new int[6];

        // Roll the dice 25000 times and display
        // the results to the console.
        for (int x = 0; x < totalRolls; x++)
        {
            byte roll = RollDice((byte)results.Length);
            results[roll - 1]++;
        }
        for (int i = 0; i < results.Length; ++i)
        {
            Console.WriteLine("{0}: {1} ({2:p1})", i + 1, results[i], (double)results[i] / (double)totalRolls);
        }
        rngCsp.Dispose();
    }

    // This method simulates a roll of the dice. The input parameter is the
    // number of sides of the dice.

    public static byte RollDice(byte numberSides)
    {
        if (numberSides <= 0)
            throw new ArgumentOutOfRangeException("numberSides");

        // Create a byte array to hold the random value.
        byte[] randomNumber = new byte[1];
        do
        {
            // Fill the array with a random value.
            rngCsp.GetBytes(randomNumber);
        }
        while (!IsFairRoll(randomNumber[0], numberSides));
        // Return the random number mod the number
        // of sides.  The possible values are zero-
        // based, so we add one.
        return (byte)((randomNumber[0] % numberSides) + 1);
    }

    private static bool IsFairRoll(byte roll, byte numSides)
    {
        // There are MaxValue / numSides full sets of numbers that can come up
        // in a single byte.  For instance, if we have a 6 sided die, there are
        // 42 full sets of 1-6 that come up.  The 43rd set is incomplete.
        int fullSetsOfValues = Byte.MaxValue / numSides;

        // If the roll is within this range of fair values, then we let it continue.
        // In the 6 sided die case, a roll between 0 and 251 is allowed.  (We use
        // < rather than <= since the = portion allows through an extra 0 value).
        // 252 through 255 would provide an extra 0, 1, 2, 3 so they are not fair
        // to use.
        return roll < numSides * fullSetsOfValues;
    }
}

```
另外，AES和其他加密算法的key尽量使用byte[] 有助于提高安全性

**Comment by ldqk** [comment]
当时不考虑RNGCryptoServiceProvider的原因是性能相对较差，如果照你这么说的不安全的话，那我可以考虑用借助guid来作为随机数种子;
另外，各种加密的key设计成字符串也是为了方便调用，如果需要byte的参数，我也可以考虑增加相关的重载函数，将在下次release

**Comment by ldqk** [comment]
```csharp
        /// <summary>
        /// 生成真正的随机数
        /// </summary>
        /// <param name="r"></param>
        /// <param name="maxValue"></param>
        /// <returns></returns>
        public static int StrictNext(this Random r, int maxValue = int.MaxValue)
        {
            return new Random(BitConverter.ToInt32(Guid.NewGuid().ToByteArray(), 0)).Next(maxValue);
        }
```

**Comment by hyfree** [comment]
关于GUID作为随机数的安全性请参考一下连接
https://stackoverflow.com/questions/467271/how-random-is-system-guid-newguid
https://www.cnblogs.com/jiading/p/9902835.html

Guid.NewGuid()保证了随机性和唯一性，但无法保证不可预测性，`Random(BitConverter.ToInt32(Guid.NewGuid().ToByteArray(), 0)).Next(maxValue)`并不能为你带来期望的安全性。

GUID生产的随机序列是128bit的，其中 
60 bits of timestamp 
48 bits of computer identifier 
14 bits of uniquifier
six bits are fixed


另外，通过自己研发比如MD5（Random（BitConverter.ToInt32(Guid.NewGuid().ToByteArray(), 0)）），拼接GUID，反复MD5等自研手段也是不可取的。

同时，我认为RNGCryptoServiceProvider是可以被接受的，但是我们必须区分他们的使用场景。
比如我需要生产短信验证码、邮箱验证码或者AES_Key的使用我会尽量使用安全随机数，虽然它真的很慢

但是，如果不涉及安全操作，比如随机返回一首歌曲或者图片、猜你喜欢、游戏中的随机事件，Random伪随机数是可以被接受的。


因为，我提出的建议是：

1. 你可以继续保留这个方法`StrictNext`，但是将方法注释修改为`生成随机数`，毕竟它确实无法生成一个安全随机数额φ(゜▽゜*)♪。
2. 提供一个RNGCryptoServiceProvider实现，来让调用者决定使用性能非常好的不安全随机数，还是性能比较慢的安全随机数。
2. RNGCryptoServiceProvider实现的返回值建议是byte[]
3. 【可选】为加密函数提供`byte[] key`的重载实现
4. 不推荐以下使用方式
https://github.com/ldqk/Masuit.MyBlogs/blob/1dc4f5a2b7cbecfcee3dd0ecefec506bfed2beb9/src/Masuit.MyBlogs.Core/Infrastructure/Services/UserInfoService.cs#L141

**Comment by ldqk** [comment]
即使guid是可预测的，那对于人类来说，能够预测guid的结果这种概率也几乎是没有的，所以，通过guid来生成随机数是足够安全的，即使人类要预测guid的结果，那也必然会使用一些物理攻击手段，而任何的的保护形式对于物理攻击手段都是无效的，除非你能提供一个预测guid的方法让我信服

**Comment by hyfree** [comment]
1. 从GUID算法上我们可以推断攻击GUID并不需要物理攻击手段
2. 对于物理攻击手段可以使用SE安全芯片防御（虽然这已经超出了软件概念的范畴）
3. 除非你能提供一个预测guid的方法让我信服：这个在理论上是可行的，但是得加钱(*^_^*)

**Comment by ldqk** [comment]
这样的话我依然坚定认为guid试试足够安全的，如果能够随意预测，那么非常多的系统用guid作为数据的id也是不安全的了

**Comment by hyfree** [comment]
GUID作为ID用途是没有问题的
但是作为秘钥用途，我还是持怀疑态度

**Comment by ldqk** [comment]
先这样吧，反正.NET6开始有RandomNumberGenerator这玩意儿了

**Comment by hyfree** [comment]
🌝🌝哈哈哈，.net6
