### ISSUE TITLE
在.netcore5.0项目中，使用SystemInfo.GetCPUTemperature() 无法获得cpu温度

### ISSUE THREAD

**Issue by light499960904** [ldqk/Masuit.Tools#62]
**bug**
在.netcore5.0项目中，使用SystemInfo.GetCPUTemperature() 无法获得cpu温度
**函数**
SystemInfo.GetCPUTemperature() 

**期望的结果或输出**

**使用环境:**
 - OS: windows10 1909
 - .NET Runtime NetCore5.0

**Comment by ldqk** [comment]
系统是否缺少温度传感器的关键驱动？或者是虚拟机环境？
建议使用aida64、CPU-z、ThrottleStop等软件检测，看这类硬件检测软件是否能够正确读取到CPU温度

**Comment by light499960904** [comment]
![image](https://user-images.githubusercontent.com/27767203/159210201-87c16a7a-e54b-4b56-b3c4-d8da0391690c.png)
cpuz是正常的 
aida64由于版权问题公司内无法测试 抱歉
