### ISSUE TITLE
Cannot create Archives of type: SevenZip

### ISSUE THREAD

**Issue by cfires** [ldqk/Masuit.Tools#64]
.Net Core 3.1项目
操作步骤
1、Startup中ConfigureServices添加服务
`   //注入7z和断点续传
    services.AddSevenZipCompressor().AddResumeFileResult(); `
2、构造函数注入
`private readonly ISevenZipCompressor _sevenZipCompressor;    
 public ScRecordsScreeningRepository(IWebHostEnvironment env, ISevenZipCompressor sevenZipCompressor)
        : base(dbFactory.Db(Constants.SystemDbKey), user)
        {
            _env = env;
            _sevenZipCompressor = sevenZipCompressor;
        }`
3、使用7z
`   MemoryStream ms = _sevenZipCompressor.ZipStream(new List<string>()
                {
                    @"D:\1.txt",
                    "http://ww3.sinaimg.cn/large/87c01ec7gy1fsq6rywto2j20je0d3td0.jpg",
                });`
结果：在使用时报'System.NotSupportedException:“Cannot create Archives of type: SevenZip”'

**Comment by ldqk** [comment]
ZipStream第二个参数传Zip即可

**Comment by cfires** [comment]
好了，谢谢大佬
