### ISSUE TITLE
请求添加新功能：希望可以添加自定义列头名称

### ISSUE THREAD

**Issue by jsrgckf** [ldqk/Masuit.Tools#65]
目前列头好像不支持特殊字符，包括一些括号之类的，因为是select new 出来的，只能符合c#变量命名规范，希望添加自定义列头。有个不成熟的想法，就是传参的时候再传个dictionary，里面的key作为select出来的变量，value对应实际要显示的列头名称。

**Comment by ldqk** [comment]
是哪一个功能？

**Comment by jsrgckf** [comment]
就是ToExcel()

**Comment by ldqk** [comment]
你可以select一个强类型啊，强类型的属性上打Description标签，写你的自定义列明就好了

**Comment by ldqk** [comment]
![image](https://user-images.githubusercontent.com/20254980/185284229-b6b0ed82-2079-445e-97ac-4a09056481fb.png)

**Comment by jsrgckf** [comment]
好的，明白了，谢谢
