### ISSUE TITLE
获取用户本机IP地址的方法

### ISSUE THREAD

**Issue by ShuangQingZhang** [ldqk/Masuit.Tools#7]
Masuit.Tools/Masuit.Tools.Core/Win32/Windows.cs
正常的一台机器可能会有多个IP地址，应该返回 string[] 类型吧？
以下写法是否更合适？

> public static string[] GetLocalUsedIP()
		{
			
			try
			{
				var ipList = new List<string>();
				var ipAddress = System.Net.Dns.GetHostAddresses(System.Net.Dns.GetHostName());
				foreach(var ip in ipAddress)
				{
					if(ip.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
					{
						ipList.Add(ip.ToString());
					}
				}
				return ipList.ToArray();
			}
			catch
			{
				return null;
			}
		}

**Comment by hjkl950217** [comment]
`GetHostName`
好像要废弃样。。 回头我找找我的

**Comment by ldqk** [comment]
一台机器确实有多个IP，但正在使用的只有1个，这个方法主要是用于获取正在使用的ip

**Comment by ldqk** [comment]
最新包`2.2.7.6`已经使用了更科学的方式获取本机的活动ip
``` csharp
NetworkInterface.GetAllNetworkInterfaces().Select(p => p.GetIPProperties())
.SelectMany(p => p.UnicastAddresses)
.Where(p => p.DuplicateAddressDetectionState == DuplicateAddressDetectionState.Preferred && !IPAddress.IsLoopback(p.Address))
.Select(x => x.Address).FirstOrDefault();
```
