### ISSUE TITLE
配置项可以添加更多默认行为

### ISSUE THREAD

**Issue by SmRiley** [ldqk/Masuit.Tools#70]
比如AES或者MD5的默认密钥可以在appsetting中设置之类,MD5默认密钥好像是个静态属性,但是AES的默认密钥好像是readyonly的,如果无法设置,不得每次都带上密钥么,或者在加密之上在封装一个带密钥的加解密方法?

**Comment by ldqk** [comment]
有自定义密钥的重载函数，加密解密时你可以使用自己的密钥

**Comment by SmRiley** [comment]
emmm,看到了,不过我建议这种全局选项还是应当放在配置项中.
