### ISSUE TITLE
[BUG]将接口和参数放在浏览器窗口里面打开报错

### ISSUE THREAD

**Issue by 649727360** [ldqk/Masuit.Tools#71]
**bug描述**
将接口和参数放在浏览器窗口里面打开报错

使用程序调试get和post都是可以的，但是将请求连接放到浏览器里面访问就访问不了了

请问是什么原因呢

**Comment by ldqk** [comment]
请按bug提交模板重新提交你的问题

**Comment by ldqk** [comment]
请重新描述你遇到的问题提交issue，这个issue暂时关闭了
