### ISSUE TITLE
请求添加新功能：添加更多硬件相关信息。

### ISSUE THREAD

**Issue by LHTXQ** [ldqk/Masuit.Tools#72]
添加物理处理器个数、系统唯一序列号、主板序列号、硬盘序列号等等。

**Comment by ldqk** [comment]
硬件序列号的获取暂时没研究出来，如果你有相应的代码，可以提pr

**Comment by LHTXQ** [comment]
[获取硬件信息C#代码.md](https://github.com/ldqk/Masuit.Tools/files/9809446/C.md)
这是在网上查到的。

另外没太看懂你代码，所有运行时不变的硬件信息是在每次请求时都会重新读取，还是只在第一次请求时读取，后面请求都返回第一次读取的结果？建议按后者的方式好点（放在构造函数里或者加个是否已读取的标志状态），因为读取硬件信息比较花时间。

**Comment by ldqk** [comment]
感谢分享，学习了！
另外，对于固定的硬件信息，是只获取一次，不会每次都会重新读取的，对于动态的信息，如硬件温度、硬盘网络速率之类的，会实时获取

**Comment by ldqk** [comment]
最新版本包已新增获取各种序列号的函数或属性
