### ISSUE TITLE
socket相关的代码要引用哪个命名空间？

### ISSUE THREAD

**Issue by SwingZhang** [ldqk/Masuit.Tools#73]
var tcpClient = new TcpClient(AddressFamily.InterNetwork);
Socket socket = tcpClient.ConnectSocket(IPAddress.Any,5000);
socket.SendFile("D:\\test\\1.txt",false,i =>
{
    Console.WriteLine("已发送"+i+"%");
});

**Comment by ldqk** [comment]
这个功能已经移除了，文档忘更新了
