### ISSUE TITLE
请求添加新功能：DateTime to string

### ISSUE THREAD

**Issue by ArcherTrister** [ldqk/Masuit.Tools#74]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

请详细描述一下你想要的功能，实现什么效果？

导出Excel，DateTime类型是否能直接转成时间字符串

![image](https://user-images.githubusercontent.com/35516482/199634606-377828b2-d601-40a4-b57b-000ab1c04482.png)

**Comment by ldqk** [comment]
不能，这种情况你只能自己把时间转换成你想要的格式后再写入excel

**Comment by ArcherTrister** [comment]
好的，那我重新定义一个模型来做
