### ISSUE TITLE
[BUG] MatchPhoneNumber 175号段不支持

### ISSUE THREAD

**Issue by Coolioyang** [ldqk/Masuit.Tools#75]
MatchPhoneNumber()  175号段不支持

**Comment by hjkl950217** [comment]
看了一眼，确实没有。目前是以正则来测试的。考虑一哈前3位用字字典的方案？  然后叠加长度和仅数字的判断

**Comment by ldqk** [comment]
目前看来中国手机号发展太快了，干脆直接放开校验吧，以1开头的11位数字都尻以认为是合法的手机号

**Comment by ldqk** [comment]
已支持，更新最新包解决
