### ISSUE TITLE
[BUG]文件下载功能，下载超过2g文件报错

### ISSUE THREAD

**Issue by ldcx9** [ldqk/Masuit.Tools#76]
`温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！ ` 

**bug描述**
[BUG]文件下载功能，下载超过2g文件报错

**解决方法**
Masuit.Tools.Abstractions\Net\PartialDownloader.cs
给From 和 TO 的 Int 改成 Long

**Comment by ldqk** [comment]
麻烦直接提个pr吧

**Comment by ldqk** [comment]
已修正，更新最新包即可
