### ISSUE TITLE
[BUG]下载超过8G的文件没有反应

### ISSUE THREAD

**Issue by ldcx9** [ldqk/Masuit.Tools#79]
`温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！ ` 

**bug描述**
下载超过8G的文件没有反应，未找到bug原因
**使用环境:**
 - .NET Runtime [e.g. 6.0]

**您的一些其他的想法**

**Comment by ldqk** [comment]
有尝试过IDM/ADM/NDM之类的下载器能正常下载吗？

**Comment by ldcx9** [comment]
> 有尝试过IDM/ADM/NDM之类的下载器能正常下载吗？

Idm，还有默认的浏览器内都是可以的，例如下面这个链接，8g，使用masuit就无法下载。http://testb.xiximiao.top/prr/PR2023.zip

**Comment by ldqk** [comment]
我这边测试是可以正常下载的，不知道是不是你的网络问题了
![image](https://user-images.githubusercontent.com/20254980/209758404-7660b4ae-cde0-4f7a-837b-80afe1b3ba14.png)

**Comment by ldcx9** [comment]
解决了，应该是系统temp目录下问题，下载不到里面，换了个目录就可以了
