### ISSUE TITLE
[BUG]控制台应用程序多线程下载Start方法闪退

### ISSUE THREAD

**Issue by bannednickyname** [ldqk/Masuit.Tools#80]
`温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！ ` 

**bug描述**
控制台应用程序多线程下载对象Start方法闪退

            string url = "https://831pansoft.pk855.com/xzx6/kkyun_1.3.7.exe";

            var downloader = new MultiThreadDownloader(url, @"D:\kkyun_1.3.7", 8);
            downloader.Configure(req =>
            {
                req.Referer = "https://masuit.com";
                req.Headers.Add("Origin", "https://baidu.com");
            });
            downloader.TotalProgressChanged += (sender, e) =>
            {
                var d = sender as MultiThreadDownloader;
                Console.WriteLine($"下载进度{d.TotalProgress}");
            };
            downloader.FileMergeProgressChanged += (sender, e) =>
            {
                Console.WriteLine("下载完成！");
            };
            downloader.Start();

 - OS: [Windows 11 22H2 22623.1037]
 - Version [2.5.9.1]
 - .NET Runtime [<=Framework 4.8, 6.0-7.0]

**您的一些其他的想法**

**Comment by ldqk** [comment]
闪退加个Console.ReadKey()；
