### ISSUE TITLE
请求添加新功能：取掉EFcore5.0 依赖

### ISSUE THREAD

**Issue by yanght1001** [ldqk/Masuit.Tools#81]
温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！  

请详细描述一下你想要的功能，实现什么效果？
我的项目已经有EFcore的其他版本，我引用了这个库后，EF版本有冲突。

**Comment by ldqk** [comment]
你的项目依赖的EFcore不是5.0版本的？
