### ISSUE TITLE
请求添加新功能：bcrypt加密

### ISSUE THREAD

**Issue by hao15239129517** [ldqk/Masuit.Tools#84]
https://www.nuget.org/packages/BCrypt.Net-Next

**Comment by ldqk** [comment]
？

**Comment by hjkl950217** [comment]
这个包功能是完备的，不用添加哇。 源代码地址：https://github.com/BcryptNet/bcrypt.net
如果社区已经有了，又没有二次开发需要，就没必要再复制一次来添加了
