### ISSUE TITLE
没带缓存？？就普通的内存缓存

### ISSUE THREAD

**Issue by NingLiu1998** [ldqk/Masuit.Tools#85]
没带缓存？？就普通的内存缓存，没有嘛？

**Comment by ldqk** [comment]
.NET框架自带有MemoryCache啊，你想用别的缓存的话也有其他的缓存库啊

**Comment by hjkl950217** [comment]
官方有：`Microsoft.Extensions.Caching.Memory`

**Comment by NingLiu1998** [comment]
找到了，瞎点点出来了，CacheHelper
