### ISSUE TITLE
请求添加新功能：希望增加公式计算

### ISSUE THREAD

**Issue by wapco** [ldqk/Masuit.Tools#87]
请详细描述一下你想要的功能，实现什么效果？
类似excel的公式计算，用xml描述，例子：
假如有定义变量x=2, a=1,b=2,c=3
`
<if match="x==1">
(a+b)*3
</if>
<if match="x==2">
(a-b)*3
</if>
`

以上结果计算后值为-3

**Comment by ldqk** [comment]
这种需求建议使用linq2xml搭配Z.Expressions.Eval即可实现，有现成的轮子，我就不重新造了

**Comment by wapco** [comment]
谢谢，Z.Expressions.Eval是收费的，那用DynamicExpresso应该是可以

**Comment by hjkl950217** [comment]
用[Natasha](https://github.com/dotnetcore/Natasha) 应该也可以实现类似的功能
