### ISSUE TITLE
FTP判断当前目录下指定的子目录是否存在，这个代码好像不太对劲。

### ISSUE THREAD

**Issue by azlis** [ldqk/Masuit.Tools#88]
`温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！ ` 

**bug描述**
这个方法始终返回```False```

![image](https://github.com/ldqk/Masuit.Tools/assets/33386249/5776c615-f2ae-4817-9ca4-d9c8b160e239)

**是哪个类的哪个函数出现了bug？**
- 这里写对应的类和函数名
- 
```FtpClient```类
```DirectoryExist```函数

**异常堆栈信息**
- 复制异常堆栈信息粘贴到这里

**函数入参**
- 这里写调用参数

**期望的结果或输出**

**使用环境:**
 - .NET Runtime [e.g. 6.0]

**您的一些其他的想法**

**Comment by hjkl950217** [comment]
这里的设定是基于一个`base`地址来判断的，这个`ftpclient`的base是`FtpServer `属性，你可以调试时看看这个属性。
这个方法是直接扫描`base`地址下有没有你传入的`文件夹`

**Comment by ldqk** [comment]
FTP这个类依赖的相关API都已经过时不能用了，这个库将在下一版本的包作删除处理，建议使用FluentFTP或者WinSCP这些现代化的第三方库吧
