### ISSUE TITLE
[BUG]ToChineseMoney负数不生效

### ISSUE THREAD

**Issue by KaneLeung** [ldqk/Masuit.Tools#98]
`温馨提示：提交后请保证回复及时，若长时间未回复的issue，将在超过30天以后作关闭处理！ ` 

**bug描述**
- 当数值为负数时，ToChineseMoney结果变为正数

**是哪个类的哪个函数出现了bug？**
- namespace Masuit.Tools.Strings.ToChineseMoney

**异常堆栈信息**
- 复制异常堆栈信息粘贴到这里

**函数入参**
- var temp2 = (-0.12).ToChineseMoney();
- var temp3 = (-1234).ToChineseMoney();
- var temp4 = (-1234.45).ToChineseMoney();

**期望的结果或输出**
负壹角贰分
负壹仟贰佰叁拾肆元
负壹仟贰佰叁拾肆元肆角伍分

**使用环境:**
 - OS: [Windonw11 22H2]
 - Version [Masuit.Tools.Core 2.6.7.1]
 - .NET Runtime [6.0.22]

**您的一些其他的想法**
![image](https://github.com/ldqk/Masuit.Tools/assets/24695053/d2b99657-ff78-4f2f-b4c3-750261c149a7)

**Comment by ldqk** [comment]
已修正，更新最新包即可

**Comment by KaneLeung** [comment]
我以为会从正则上入手，感谢
