### ISSUE TITLE
请问是否支持获取证书序列号

### ISSUE THREAD

**Issue by successgo** [ldqk/Masuit.Tools#99]
像在对接支付宝开放平台时，要求使用证书序列号

**Comment by ldqk** [comment]
啥意思啊，没懂

**Comment by successgo** [comment]
不好意思，我重新描述一下：
想请教一下，如何获取证书序列号 SN ？

<img width="544" alt="image" src="https://github.com/ldqk/Masuit.Tools/assets/13791720/e9029c13-b11c-4b98-9b80-f8e221ba9e70">

**Comment by ldqk** [comment]
没有这样的功能，你可以尻虑用系统自带的X509Certificate类试试看

**Comment by successgo** [comment]
ok
